version: "3.9"

services:
  webapp:
    restart: always
    build: ./
    container_name: 'tictactoe'
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "uvicorn main:app --reload --port 8000 --host 0.0.0.0"
