version: "3.9"

services:
  web:
    build: ./nginx
    container_name: 'nginx'
    ports:
      - 80:80
    depends_on:
      - webapp
    volumes:
      - static_volume:/home/app/static

  webapp:
    restart: always
    build: ./
    container_name: 'tictactoe'
    volumes:
      - ./:/app
      - static_volume:/app/static
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    command: >
      sh -c "uvicorn main:app --port 8000 --host 0.0.0.0"

volumes:
  static_volume:
